---
- name: Установить Docker CE
  hosts: web_vms
  become: yes
  roles:
    - docker

- name: Развернуть echo-приложение в Docker
  hosts: web_vms
  become: yes
  roles:
    - app_deploy

- name: Настроить nginx-балансировщик
  hosts: web_vms
  become: yes
  roles:
    - nginx_lb
