Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false

  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  config.vm.network "forwarded_port",
    guest: 22, host: 2222, host_ip: "0.0.0.0"

  config.vm.synced_folder ".", "/vagrant", disabled: true
end
