---
- name: Установить базовые зависимости для добавления репозитория
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: Импортировать GPG-ключ Docker в глобальный keyring
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Добавить официальный репозиторий Docker CE
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: docker
    update_cache: yes
    state: present

- name: Установить Docker CE и сопутствующие пакеты
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
