apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "echo-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "echo-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "echo-chart.name" . }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AUTHOR
              value: "{{ .Values.author }}"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
